### ISSUE TITLE
为什么不采用逆向最大匹配的算法

### ISSUE THREAD

**Issue by zhaoweijing2003** [zhengchun/CWSharp#1]
逆向最大匹配算法的效果要不正向最大匹配算法的效果好很多，为啥不支持逆向呢？

**Comment by zhengchun** [comment]
正向匹配和逆向匹配都是中文分词切分的方法。
CWSharp基于字典的正向匹配的方法来切分所有词组组合，然后通过其它规则来最终确认一个词组。所以这里采用逆向或正向没有本质区分。
[MMSeg分词算法简述](http://blog.sina.com.cn/s/blog_43b8e6dd0100ne6e.html) 应该能帮助你。
